### ISSUE TITLE
error @ build or run or compile

### ISSUE THREAD

**Issue by neerajsingh** [AlanQuatermain/go-tmbundle#10]
i am not sure if this is the best place to raise this....i get this error when i try to compile with a golang bundle. i hoping somebody can help me resolve this issue. prog compiles and works fine using command line -

:29:in `require': no such file to load -- /Applications/TextMate.app/Contents/SharedSupport/Support/lib/Builder (LoadError) from :29:in`require' from /Users/ns/Library/Application Support/TextMate/Bundles/Go.tmbundle/Support/goerrs.rb:3:in `' from :29:in`require' from :29:in `require' from /Users/ns/Library/Application Support/TextMate/Bundles/Go.tmbundle/Support/gomate.rb:5:in`' from :29:in `require' from :29:in`require' from /tmp/temp_textmate.KoOLaG:3:in `'

**Comment by mkhl** [comment]
TextMate “recently” (2010-12-07) removed the Builder library from
Support, it seems bundles requiring it are expected to bundle it
themselves. I guess that means one of us will have to either do that or
use something else to generate HTML.

**Comment by neerajsingh** [comment]
Thanks...i should have noticed the issues raised earlier. There was a thread on a similar error posted earlier
