### ISSUE TITLE
Couldn't find g

### ISSUE THREAD

**Issue by schmurfy** [AlanQuatermain/go-tmbundle#13]
Hi,
I tried using the bundle to give go a try but I cannot make it works. Go is installed by homebrew and I have all the go\* binaries in my path but when I hit Apple+R all I get is an error "Couldn't find g" with all the locations in the search PATH printed below.

I tried to find where the error occured in the code without luck (the path followed is not easy to find with one executable calling another and another including another one xD).

Any idea what could go wrong ?

**Comment by puchupala** [comment]
I also use Homebrew's Go too. Maybe Go binary isn't in your PATH. You could try my fork and manually specify GOBIN to /path/to/homebrew/bin in Textmate. https://github.com/KnightBaron/go-tmbundle

**Comment by schmurfy** [comment]
I will try your fork when I get the chance but what I really don't understand is why it is looking for "g" where as far as I know there is no such binary in the go suite Oo

**Comment by puchupala** [comment]
The script prefix "g" to 5g, 6g and 8g as necessary depends on the platform compiling. I forgot the detail but I remember that I got the same error and fixed that on my fork before.

**Comment by schmurfy** [comment]
I found the problem thanks to your fork which did not work but helped me find the issue:
I have a macbook pro under Lion and the reported value for "sysctl -n hw.machine" is "x86_64" which is unknown by the goarch script (btw it is really weird that the number before the "g" represents the architecture, it is a little scary) so the architecture "number" was an empty string resulting in gobin trying to run "g".

**Comment by AlanQuatermain** [comment]
Closing as this was fixed by schmurfy— thanks for your help.

**Comment by schmurfy** [comment]
no problem, I was sure I had closed this issue but I must have forgotten to submit it xD
