### ISSUE TITLE
Won't tidy up since recent changes in gofmt (again)

### ISSUE THREAD

**Issue by iMax-pp** [AlanQuatermain/go-tmbundle#2]
When invoking the "Tidy" command with the last release of go, the command fails because gofmt doesn't support the -oldparser option anymore.

**Comment by AlanQuatermain** [comment]
Fixed in version 1.0.3. Sigh. Sorry for the long wait. iPad release crunch, y'know.

**Comment by iMax-pp** [comment]
You're welcome. :-)
In fact I fixed the issue on my version, but I reported it for others.
