### ISSUE TITLE
Won't Run if the .go File is in a Folder with a Space in the Name

### ISSUE THREAD

**Issue by wasokeli** [AlanQuatermain/go-tmbundle#3]
I'm not sure what stage it fails at, but it treats the part of the filename before the space as the entire filename.
For instance, if the .go file resides in 
    /Users/kelsey/One Two/
, the Run command fails with
    <epoch>: fatal error: open /Users/kelsey/One:: No such file or directory

**Comment by AlanQuatermain** [comment]
I've just pushed a fix for this, but I don't have Go installed on this machine to test it right now. Please re-open the bug if you still see an issue.
