### ISSUE TITLE
jumping to error line is broken

### ISSUE THREAD

**Issue by guncha** [AlanQuatermain/go-tmbundle#5]
When compiling (⌘K), if there's an error in compiler output, clicking on it's link jumps to the file in question, but not the offending line. It happens because the following TextMate link is generated:

txmt://open?line=&url=file:///Users/gunca/Desktop/test.go

TextMate Version 1.5.10 (1623)
Bundle version: tip

**Comment by AlanQuatermain** [comment]
I'll have to dig about in the TextMate ruby scripts to figure this one out properly. Hopefully I'll get some time to fix it over the next few days.

**Comment by guncha** [comment]
Hey! I looked at the problem and it's really trivial. The problem is in `goerrs.rb:Go::href(file, line)`. The function gets correct arguments, but simply doesn't print them properly. I'll open a pull request.
